### ISSUE TITLE
Sign Up page has issue with Email API. Won't let user sign up. Error: Email API failed to process request.

### ISSUE THREAD

**Issue by SrisaivikasMunagala** [Allen-ISD-Computer-Science/IRL_DutySchedule_2024#32]

**Comment by ryanhallock** [comment]
Can you retest this issue @SrisaivikasMunagala with the latest branch and see what you get? I have improved error handling in the latest development branch.

**Comment by SrisaivikasMunagala** [comment]
I have retested and got this error: serverError(reason: "Email API failed to process request because of `Abort.404: Specified template external ID \'5FA3B955-761D-11EE-B513-0242C0A83002\' was not found for this apiKey.`") @ryanhallock

**Comment by ryanhallock** [comment]
Please use the new API key in discord.

**Comment by SrisaivikasMunagala** [comment]
Just retested with the new API key. Same error: serverError(reason: "Email API failed to process request because of `Abort.404: Specified template external ID \'5FA3B955-761D-11EE-B513-0242C0A83002\' was not found for this apiKey.`") @ryanhallock
