### ISSUE TITLE
Calendar to view duties

### ISSUE THREAD

**Issue by jishnud17** [Allen-ISD-Computer-Science/IRL_DutySchedule_2024#4]

**Comment by brett-k-cs** [comment]
- API Call for Next Duty & append
- API Call for 5-day calendar on dashboard
- API Call for 31-day calendar on separate page

**Comment by brett-k-cs** [comment]
- [x] API Call for 31-day calendar on separate page

**Comment by brett-k-cs** [comment]
[x] API Call for 5-day calendar on dashboard

**Comment by brett-k-cs** [comment]
Bug (All fixed):
- [x] If back/forth, events stack

**Comment by brett-k-cs** [comment]
Added:

- [x] A/B day indicator for dashboard calendar view
