### ISSUE TITLE
Not able to submit CSV file

### ISSUE THREAD

**Issue by saip9** [Allen-ISD-Computer-Science/IRL_DutySchedule_2024#40]
I am getting an error when trying to submit a sample CSV file.

Screenshots:

![Image](https://github.com/Allen-ISD-Computer-Science/IRL_DutySchedule_2024/assets/89651922/f8e87632-66a4-474b-bd33-2a8bde7da2a5)

![Image](https://github.com/Allen-ISD-Computer-Science/IRL_DutySchedule_2024/assets/89651922/8e005303-eac0-4d2a-8455-cc2ff31719b7)

**Comment by SrisaivikasMunagala** [comment]
Update: Tried with actual CSV files with staff and still got same error.

**Comment by jishnud17** [comment]
Not needed anymore
