### ISSUE TITLE
Add a unique "id" column to all views.

### ISSUE THREAD

**Issue by ryanhallock** [Allen-ISD-Computer-Science/IRL_DutySchedule_2024#43]
Due to limitations in vapors fluent. Views cannot be represented. So you have to use a Model, but they come with some ID.

We could use ROW_NUMBER() in SQL to create a 1 to 1 relationship. The ID value doesn't matter, but if we want to sort a list of information quickly, we should use a unique ID. The problem with adding ROW_NUMBER() is that it can change through queries, but it must be a documented limitation to band-aid another.

**Comment by Muq2** [comment]
fixed in https://github.com/Allen-ISD-Computer-Science/IRL_DutySchedule_2024/commit/861c0308d0070593130dd7a598ed9e101cf42664
