### ISSUE TITLE
Duty Dashboard

### ISSUE THREAD

**Issue by saip9** [Allen-ISD-Computer-Science/IRL_DutySchedule_2024#6]
Here is the Duty Dashboard design that I created on 10/10/2023. 

![Image](https://github.com/Allen-ISD-Computer-Science/IRL_DutySchedule_2024/assets/89651922/267107c1-3be0-43cd-826e-677b755782ca)

@brett-k-cs Brett Kaplan, could you please work on transforming the design into code? Let me know if you have any questions. I would like this completed by November 1. Remember to submit the [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSeXIjwCithFUn7Yog8X2a3DqsjHlY_d45JH062Lzl2mjoW_lQ/viewform) by 8 PM each day. Please be detailed in what you accomplished while filling out the form.

**Comment by brett-k-cs** [comment]
Me & Pranav added all of the content on the page
